# Generated by Django 4.2.4 on 2023-09-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resumedata_academic_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='test_score',
            field=models.IntegerField(default=0),
        ),
    ]
