# Generated by Django 4.2.4 on 2023-09-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resumedata_test_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='skill_rank',
            field=models.JSONField(default=[]),
        ),
    ]
