# Generated by Django 4.2.4 on 2023-09-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resumedata_skill_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='skill_rank',
            field=models.JSONField(),
        ),
    ]
